.github/workflows/pull_request.yml, src/common/meta/GflagsManager.cpp
Integer `Value`'s type name is `int`.
=> Fix integer flags conversion

src/common/expression/LogicalExpression.cpp
=> Fix operator name

src/common/expression/VariableExpression.h
=> Fix VariableExpression

src/common/expression/Expression.cpp, src/common/expression/VariableExpression.h, src/common/expression/test/ExpressionTest.cpp
=> Fix variable expression decode error

src/common/expression/ArithmeticExpression.h, src/common/expression/AttributeExpression.h, src/common/expression/ConstantExpression.h, src/common/expression/ContainerExpression.h, src/common/expression/EdgeExpression.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/FunctionCallExpression.h, src/common/expression/LabelAttributeExpression.h, src/common/expression/LabelExpression.h, src/common/expression/LogicalExpression.h, src/common/expression/PropertyExpression.h, src/common/expression/RelationalExpression.h, src/common/expression/SubscriptExpression.h, src/common/expression/TypeCastingExpression.h, src/common/expression/UUIDExpression.h, src/common/expression/UnaryExpression.h, src/common/expression/VariableExpression.h, src/common/expression/VertexExpression.h, src/common/expression/test/EncodeDecodeTest.cpp, src/common/expression/test/ExpressionTest.cpp
Replace decode/encode with construction
Disable variable expression decode function.
=> Reimplement clone interface of expression

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/clients/storage/GraphStorageClient.cpp, src/common/clients/storage/GraphStorageClient.h, src/common/interface/meta.thrift, src/common/interface/storage.thrift
=> Support integer vertex id.

src/common/expression/ContainerExpression.h
=> Set single item for list/set/map expressions

src/common/clients/meta/MetaClient.cpp, src/common/interface/meta.thrift
this pr is to simplify the column type usage in nebula graph repo
=> Extract property and length of type to ColumnTypeDef

src/common/clients/meta/MetaClient.cpp, src/common/interface/meta.thrift
=> Update vid definition in space description struct

src/common/interface/meta.thrift
fix error in vesoft-inc/nebula-storage#147
=> Set default value for vid type in space description

src/common/interface/storage.thrift
As title, the interface is almost same as 1.0.
=> scan interface

src/common/datatypes/Date.h, src/common/datatypes/Value.cpp, src/common/datatypes/test/ValueTest.cpp
1. added constructor and < comparator for time and datetime
2. updated ValueTest.cpp regarding time and datetime
=> add <comparator for time and datetime

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/storage.thrift, src/common/meta/IndexManager.h, src/common/meta/ServerBasedIndexManager.cpp, src/common/meta/ServerBasedIndexManager.h
support get all vertice on tag, get all edges on edgetype
=> support get all vertice on tag, get all edges on edgetype

src/common/expression/ContainerExpression.h, src/common/expression/FunctionCallExpression.h, src/common/expression/TypeCastingExpression.h, src/common/expression/UnaryExpression.h
=> Avoid items copy in container expression

cmake/nebula/NebulaCMakeMacros.cmake
ld.bfd does not support this feature. Let's take care of this later.
=> Fixed --gdb-index

src/common/clients/storage/GraphStorageClient.cpp, src/common/clients/storage/GraphStorageClient.h
(cherry picked from commit fe4921b52fd265451a7f56c76ad03b2e6084d83a)
=> [cherrypick] cherrypick #282 to alpha branch

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift, src/common/interface/storage.thrift
Get the statistics of the current space through the following syntax：
```
submit job statis
show status,
```
=> Support space level statistics

src/common/expression/CMakeLists.txt, src/common/expression/CaseExpression.cpp, src/common/expression/CaseExpression.h, src/common/expression/ExprVisitor.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/test/EncodeDecodeTest.cpp, src/common/expression/test/ExpressionTest.cpp
http://jira.nebula-graph.io:8081/projects/NG/issues/NG-281?filter=allissues
Based on:
https://github.com/vesoft-inc/nebula-graph/pull/353
https://github.com/vesoft-inc/nebula-storage/pull/183
=> Support case expression

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift, src/common/meta/Common.h
Modify listener interface in meta client, needed by https://github.com/vesoft-inc/nebula-storage/pull/180.
=> Modify listener interface in meta client

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift, src/common/meta/Common.h
Reverts vesoft-inc/nebula-common#285
=> Revert "Modify listener interface in meta client"

src/common/expression/CMakeLists.txt, src/common/expression/ExprVisitor.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/PathBuildExpression.cpp, src/common/expression/PathBuildExpression.h, src/common/expression/test/EncodeDecodeTest.cpp, src/common/expression/test/ExpressionContextMock.cpp, src/common/expression/test/ExpressionTest.cpp
https://github.com/vesoft-inc/nebula-storage/pull/193
https://github.com/vesoft-inc/nebula-graph/pull/392
=> Build path expr.

src/common/expression/LogicalExpression.cpp, src/common/expression/LogicalExpression.h, src/common/expression/test/EncodeDecodeTest.cpp
This refactor helps on the upcoming boolean expression analysis.
=> Flatten LogicalExpression

src/common/clients/meta/MetaClient.cpp
=> Modify folly::hash::fnv64_buf to MurmurHash2

src/common/interface/meta.thrift
=> change tagId/edgeType to tagName/edgeName in StatisItem

cmake/nebula/LinkerConfig.cmake, src/common/base/GdbDebugScript.cpp
=> Disable --gc-sections if ENABLE_GDB_SCRIPT_SECTION

src/common/base/ObjectPool.h, src/common/base/test/CMakeLists.txt, src/common/base/test/ObjectPoolTest.cpp
Necessary to refactor the AST node management.
=> Move ObjectPool into nebula-common

src/common/expression/LogicalExpression.h
=> Add LogicalExpression::setOperands

src/common/context/ExpressionContext.h, src/common/expression/BinaryExpression.cpp, src/common/expression/CMakeLists.txt, src/common/expression/ColumnExpression.cpp, src/common/expression/ColumnExpression.h, src/common/expression/ConstantExpression.cpp, src/common/expression/ExprVisitor.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/FunctionCallExpression.cpp, src/common/expression/LabelExpression.cpp, src/common/expression/PropertyExpression.cpp, src/common/expression/TypeCastingExpression.cpp, src/common/expression/UUIDExpression.cpp, src/common/expression/UnaryExpression.cpp, src/common/expression/test/ExpressionContextMock.cpp, src/common/expression/test/ExpressionContextMock.h, src/common/expression/test/ExpressionTest.cpp
background  is  https://www.yuque.com/nebulagraph/emchnb/kg2u5m
=> add columnExpression

src/common/base/Base.h, src/common/context/ExpressionContext.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/RelationalExpression.cpp, src/common/expression/test/ExpressionContextMock.h, src/common/expression/test/ExpressionTest.cpp
Depends on:
https://github.com/vesoft-inc/nebula-graph/pull/414
https://github.com/vesoft-inc/nebula-storage/pull/217
=> support regular expression

src/common/datatypes/Value.cpp, src/common/expression/LabelAttributeExpression.h, src/common/expression/test/ExpressionTest.cpp
Needed by vesoft-inc/nebula-graph#434
=> Update label attribute expression construction and fix empty value computation

src/common/graph/Response.h, src/common/interface/graph.thrift
relevant: https://github.com/vesoft-inc/nebula-graph/pull/454
Please be aware that this change requests all client to update
=> fix ErrorCode typo

cmake/ThriftGenerate.cmake
=> update go thrift package path

src/common/clients/meta/MetaClient.cpp, src/common/interface/meta.thrift
please refers to https://github.com/vesoft-inc/nebula-graph/pull/437
=> Show host graph

.linters/cpp/cpplint.py
Reverts vesoft-inc/nebula-common#312
=> Revert "Upgrade cpplint.py"

src/common/clients/meta/MetaClient.cpp, src/common/interface/common.thrift, src/common/interface/meta.thrift, src/common/interface/storage.thrift
Reverts vesoft-inc/nebula-common#288
storage won't compile, wait br ready.
=> Revert "Added an API for backup."

src/common/clients/storage/GraphStorageClient.cpp, src/common/clients/storage/InternalStorageClient.cpp, src/common/clients/storage/InternalStorageClient.h, src/common/clients/storage/StorageClientBase.h, src/common/clients/storage/StorageClientBase.inl
=> internal storage client needs to retry using a different port 

cmake/nebula/GitInfoConfig.cmake, src/common/base/Base.cpp, src/common/base/Base.h
=> Move versionString to graph and storage repos

src/common/clients/meta/MetaClient.cpp
refer to : 
https://github.com/vesoft-inc/nebula/pull/2433
=> cherry patch from nebula 1.0 

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/meta/SchemaManager.h, src/common/meta/ServerBasedSchemaManager.cpp, src/common/meta/ServerBasedSchemaManager.h
Add getAllLatestTagSchema() which returns the latest version of schemas of all tags in the given space.
related PRs:
https://github.com/vesoft-inc/nebula-storage/pull/288
https://github.com/vesoft-inc/nebula-graph/pull/553
=> Add getAllLatestVerTagSchema()

src/common/clients/storage/GraphStorageClient.cpp, src/common/interface/storage.thrift
=> Fix set and unify limit

src/common/expression/CMakeLists.txt, src/common/expression/ExprVisitor.h, src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/ListComprehensionExpression.cpp, src/common/expression/PredicateExpression.cpp, src/common/expression/ReduceExpression.cpp, src/common/expression/ReduceExpression.h, src/common/expression/test/EncodeDecodeTest.cpp, src/common/expression/test/ExpressionContextMock.h, src/common/expression/test/ExpressionTest.cpp
https://github.com/vesoft-inc/nebula-graph/pull/479 depends on this pr.
doc:https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-reduce
=> Support reduce expression

src/common/thrift/ThriftTypes.h
Will change the format of edge key 
from
type(1) + partId(3) + srcId(*) + edgeType(4) + edgeRank(8) + dstId(*) + ***version(8)***
to 
type(1) + partId(3) + srcId(*) + edgeType(4) + edgeRank(8) + dstId(*) + ***version(1)***
=> change ver of edge key from i64 to char

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
Fix https://github.com/vesoft-inc/nebula-graph/issues/710
=> fix properties(MAP)

src/common/expression/SubscriptExpression.cpp, src/common/expression/test/ExpressionTest.cpp
Fix https://github.com/vesoft-inc/nebula-graph/issues/694
=> Enhance subscript expression

src/common/datatypes/Value.cpp, src/common/datatypes/test/ValueTest.cpp, src/common/expression/AggregateExpression.cpp, src/common/expression/test/ExpressionTest.cpp
Fix [https://github.com/vesoft-inc/nebula-graph/issues/678](https://github.com/vesoft-inc/nebula-graph/issues/678)
=> fix agg and List operator

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/720](https://github.com/vesoft-inc/nebula-graph/issues/720)
=> fix null toString

src/common/interface/storage.thrift
For PR : 
https://github.com/vesoft-inc/nebula-storage/pull/355
=> Add error code for index write

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
Add pi(), e(), radians() to be compatible with openCypher.
fixes https://github.com/vesoft-inc/nebula-graph/issues/717 , fixes https://github.com/vesoft-inc/nebula-graph/issues/718 , fixes https://github.com/vesoft-inc/nebula-graph/issues/719
=> Add mathematical functions

src/common/datatypes/Value.cpp, src/common/datatypes/test/ValueTest.cpp
=> Add bound check to int() and update tests for type casting

src/common/expression/TypeCastingExpression.cpp
https://discuss.nebula-graph.com.cn/t/topic/2981
=> empty to INT OR FLOAT

src/common/datatypes/Value.cpp, src/common/function/test/FunctionManagerTest.cpp
fix  toBoolean(null),toFloat(null),toBoolean(null)
=> fix typeCasting function

src/common/datatypes/Value.cpp, src/common/datatypes/test/ValueTest.cpp
Change Value::operator back to the origin.
=> Fix value operator

src/common/expression/Expression.cpp, src/common/expression/Expression.h, src/common/expression/UnaryExpression.cpp, src/common/expression/test/ExpressionTest.cpp
Add `IS NULL` and `IS NOT NULL`
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/701](https://github.com/vesoft-inc/nebula-graph/issues/701)
=> Add isNull/isNotNull operator

src/common/expression/Expression.h
Small changes to avoid problems that may be encountered in different versions of meta upgrades.
=> small fix for upgrade

src/common/expression/UnaryExpression.cpp, src/common/expression/test/ExpressionTest.cpp
=> fix toString of IS_NULL

src/common/plugin/fulltext/test/FulltextPluginTest.cpp
=> fixed unstable test plugin_fulltext_test

src/common/expression/RelationalExpression.cpp, src/common/expression/test/ExpressionTest.cpp
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/702](https://github.com/vesoft-inc/nebula-graph/issues/702) and fixes [https://github.com/vesoft-inc/nebula-graph/issues/652](https://github.com/vesoft-inc/nebula-graph/issues/652)
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/814](https://github.com/vesoft-inc/nebula-graph/pull/814)
=> fix in operator

src/common/function/FunctionManager.cpp
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/816](https://github.com/vesoft-inc/nebula-graph/issues/816)
=> add rand function

src/common/webservice/GetFlagsHandler.cpp, src/common/webservice/test/FlagsAccessTest.cpp
fix https://github.com/vesoft-inc/nebula-storage/issues/409
=> fix missing type in getFlags

src/common/plugin/fulltext/test/FulltextPluginTest.cpp
=> fixed unstable testcase

src/common/datatypes/Path.cpp, src/common/datatypes/test/CMakeLists.txt, src/common/datatypes/test/PathTest.cpp, src/common/datatypes/test/ValueBenchmark.cpp
benchmark between string and value.
=> Fix path duplicate functions and add value hash/equal benchmark

src/common/expression/Expression.h, src/common/expression/LogicalExpression.h, src/common/expression/RelationalExpression.h
Add `isLogicalExpr()` and `isRelExpr()`
=> Add interfaces to expression

src/common/expression/ArithmeticExpression.h, src/common/expression/Expression.h
=> [Simple] Add isArithmeticExpr() to expression

src/common/time/Duration.cpp, src/common/time/Duration.h, src/common/time/WallClock.cpp, src/common/time/detail/TscHelper.cpp, src/common/time/detail/TscHelper.h, third-party/install-gcc.sh, third-party/install-third-party.sh
=> Support aarch64

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
cherry picked from commit c93c0e62537d711b1e2443877beb453a5ccfdeee
=> Cherrypick #491

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift
as title
related storage pr(this two have to merge together):
https://github.com/vesoft-inc/nebula-storage/pull/418
=> Send leader term in heart beat

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift
Reverts vesoft-inc/nebula-common#485
=> Revert "Send leader term in heart beat"

src/common/function/FunctionManager.cpp, src/common/function/FunctionManager.h
As title.
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/926](https://github.com/vesoft-inc/nebula-graph/pull/926)
=> fix case sensitivity of function name

src/common/clients/meta/MetaClient.cpp, src/common/interface/meta.thrift
=> add invalid job errorcode

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/interface/meta.thrift
Reverts vesoft-inc/nebula-common#499
=> Revert "Revert "Send leader term in heart beat""

cmake/ThriftGenerate.cmake
It's seems caused by the graph/storage configure the common together.
=> Ignore the mv issue first.

src/common/expression/RelationalExpression.cpp, src/common/expression/test/ExpressionTest.cpp
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/972](https://github.com/vesoft-inc/nebula-graph/pull/972)
=> fix some relational expressions with Null/badNull

src/common/expression/PredicateExpression.cpp
As title.
Dependency of https://github.com/vesoft-inc/nebula-graph/pull/973
=> [opencypher compatibility] Support using exists with dynamic map

src/common/expression/LabelAttributeExpression.h
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/975](https://github.com/vesoft-inc/nebula-graph/pull/975)
=> add non-const getter for LabelAttrExpr

src/common/interface/storage.thrift
=> add errorcode for update

src/common/clients/meta/MetaClient.cpp, src/common/clients/meta/MetaClient.h, src/common/clients/storage/InternalStorageClient.cpp, src/common/clients/storage/InternalStorageClient.h, src/common/clients/storage/StorageClientBase.h, src/common/clients/storage/StorageClientBase.inl, src/common/interface/common.thrift, src/common/interface/graph.thrift, src/common/interface/meta.thrift, src/common/interface/storage.thrift
Only For removing `kvstore::ResultCode`
https://github.com/vesoft-inc/nebula-graph/pull/1022 and https://github.com/vesoft-inc/nebula-storage/pull/448 reply on this pr.
=> remove kvstore::ResultCode

cmake/ThriftGenerate.cmake
=> Update go module

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
=> add typeid

src/common/function/FunctionManager.cpp, src/common/function/test/FunctionManagerTest.cpp
=> [Bug fix] fix src() and dst() for reversed edge

src/common/base/CMakeLists.txt, src/common/base/Memory.cpp, src/common/base/Memory.h, src/common/base/test/CMakeLists.txt, src/common/base/test/MemoryTest.cpp
refer to vesoft-inc/nebula-graph#1052
=> Add memory info to get system memory usage

cmake/nebula/GeneralCompilerConfig.cmake, src/common/datatypes/Date.cpp, src/common/datatypes/Date.h, src/common/datatypes/DateOps.inl, src/common/datatypes/Value.cpp, src/common/datatypes/Value.h
* Use pointer instead of inlined value for `std::string`
* Use bit fields in `DateTime`
=> Shrink sizeof Value struct

src/common/datatypes/Date.cpp, src/common/datatypes/Date.h, src/common/datatypes/DateOps.inl, src/common/datatypes/Value.cpp, src/common/datatypes/Value.h
=> Revert"Shrink sizeof Value struct"

src/common/expression/Expression.h, src/common/expression/ListComprehensionExpression.cpp, src/common/expression/ListComprehensionExpression.h, src/common/expression/PredicateExpression.cpp, src/common/expression/PredicateExpression.h, src/common/expression/ReduceExpression.cpp, src/common/expression/ReduceExpression.h
Reverts vesoft-inc/nebula-common#542
=> Revert "Add rawString interface for expression"

src/common/datatypes/DataSet.h
This change will let us construct DataSet by following two ways:
```c++
const std::vector<std::string> &columns = node->colNames();
DataSet ds(columns);
std::vector<std::string> columns;
columns.emplace_back("kVid");
DataSet ds(std::move(columns));
```
=> Update dataset constructor

src/common/expression/Expression.h, src/common/expression/ListComprehensionExpression.cpp, src/common/expression/ListComprehensionExpression.h, src/common/expression/PredicateExpression.cpp, src/common/expression/PredicateExpression.h, src/common/expression/ReduceExpression.cpp, src/common/expression/ReduceExpression.h
=> Reopen PR: Add rawString interface

src/common/clients/meta/MetaClient.cpp
=> fix checkPartExistInCache

src/common/clients/storage/GraphStorageClient.cpp, src/common/clients/storage/GraphStorageClient.h, src/common/clients/storage/StorageClientBase.h, src/common/datatypes/HostAddr.h
https://github.com/vesoft-inc/nebula-cpp/pull/28 depends on this.
=> add scan edge interface in GraphStorageClient

src/common/expression/FunctionCallExpression.cpp, src/common/function/FunctionManager.cpp, src/common/function/FunctionManager.h, src/common/function/test/FunctionManagerTest.cpp
Close https://github.com/vesoft-inc/nebula-graph/issues/1164
Pass the arguments of function by reference to avoid copy data.
=> Pass the arguments of function by reference to avoid copy.

src/common/datatypes/Path.cpp, src/common/plugin/fulltext/FTGraphAdapter.h
=> Avoid rehash for duplicate path check functions

CMakeLists.txt
close https://github.com/vesoft-inc/nebula-graph/issues/1181
=> Modify require cmake version

src/common/expression/ContainerExpression.h, src/common/expression/Expression.h
As title.
This interface will be used in https://github.com/vesoft-inc/nebula-graph/pull/1278
=> Add isContainerExpr() interface

src/common/clients/meta/MetaClient.cpp
cherry-pick https://github.com/vesoft-inc/nebula-common/pull/592
=> fix download to leader

src/common/datatypes/Value.cpp, src/common/datatypes/test/ValueTest.cpp
As title.
Required by https://github.com/vesoft-inc/nebula-graph/pull/1337
Fix https://github.com/vesoft-inc/nebula-graph/issues/1327
=> Fix parsing scientific notation string and add UTs

src/common/thrift/ThriftClientManager.inl
sync with master
https://github.com/vesoft-inc/nebula/pull/2567
=> use un-resolved host as client-map key
