src/common/context/ExpressionContext.h
src/common/expression/AttributeExpression.cpp
src/common/expression/AttributeExpression.h
src/common/expression/CMakeLists.txt
src/common/expression/EdgeExpression.cpp
src/common/expression/EdgeExpression.h
src/common/expression/Expression.cpp
src/common/expression/Expression.h
src/common/expression/LabelAttributeExpression.cpp
src/common/expression/LabelAttributeExpression.h
src/common/expression/LabelExpression.cpp
src/common/expression/LabelExpression.h
src/common/expression/PropertyExpression.cpp
src/common/expression/PropertyExpression.h
src/common/expression/VertexExpression.cpp
src/common/expression/VertexExpression.h
src/common/expression/test/EncodeDecodeTest.cpp
src/common/expression/test/ExpressionBenchmark.cpp
src/common/expression/test/ExpressionContextMock.h
src/common/expression/test/ExpressionTest.cpp

* Add `AttributeExpression` to denote the form `<expr>.label`
* Add `EdgeExpression` and `VertexExpression` to represent the Vertex and Edge object internally.
* Rename `SymbolPropertyExpression` to `PropertyExpression`, AKA. the base class of all property-related expressions.
* Add `LabelAttributeExpression` to denote an unresolved expression of the form `label.label`. Thus all `PropertyExpression` are deterministic now.

Add AttributeExpression

---

src/common/expression/LabelAttributeExpression.h
src/common/expression/LabelExpression.h
src/common/expression/LogicalExpression.cpp

Because now we are using encode and decode to implement expression clone, we have to override relative methods.

Add encode/decode to LabelAttributeExpression

---

src/common/expression/Expression.cpp
src/common/expression/Expression.h
src/common/expression/test/ExpressionTest.cpp

This clone is a deep copy of original expression object.
To simplify the following use case:
```cpp
Expression *expr = ...;
auto cloneExpr = Expression::decode(Expression::encode(*expr));
// =>
auto cloneExpr = expr->clone();
```

Add clone interface for expression

---

src/common/meta/SchemaManager.cpp
src/common/meta/SchemaManager.h

This interface will be used by `Graph Layer` and `Storage Layer` later. 
It's to avoid some duplicate check when operate the indexes.

Support getSchemaIDByName in SchemaManager

---

src/common/expression/Expression.cpp
src/common/expression/Expression.h
src/common/expression/RelationalExpression.cpp
src/common/expression/test/ExpressionTest.cpp

regarding issue: fixes #252 
1. added StartsWith() and EndsWith() in RelationalExpression.cpp
2. updated test cases for new functions

added StartsWith() and EndsWith() in RelationalExpression.cpp

---

src/common/meta/SchemaManager.h
src/common/meta/ServerBasedSchemaManager.cpp
src/common/meta/ServerBasedSchemaManager.h

To fix https://github.com/vesoft-inc/nebula-storage/issues/170 and https://github.com/vesoft-inc/nebula-storage/issues/166, storage need to be aware of vid type. And can trim trailing \0 if the space vid is string with fixed length.
Needed by https://github.com/vesoft-inc/nebula-storage/pull/172.

add getSpaceVidType

---

src/common/expression/LogicalExpression.cpp
src/common/expression/test/ExpressionTest.cpp

The `&&` and `||` format will not be supported.

Rename &&/|| to AND/OR

---

cmake/nebula/ConfigNebulaCommon.cmake
cmake/nebula/GeneralCMakeOptions.cmake
src/common/base/CMakeLists.txt
src/common/base/GdbDebugScript.cpp

Because we link against libstdc++ statically, GDB cannot automatically load pretty printers for STL data structures. This PR add an option to add a special ELF section to each executable to load those printers.

Add .debug_gdb_scripts section to improve debugging experience

---

.gitignore
src/common/datatypes/Path.h
src/common/expression/PathBuildExpression.cpp
src/common/expression/test/ExpressionContextMock.cpp
src/common/expression/test/ExpressionTest.cpp
src/common/function/FunctionManager.cpp

Now we can use path builder expression to build the path for following cases:
1. V
2. V, E
3. V, Path
4. Path, V, E
5. Path, Path
6. Path, V, Path

Enhance path build expression

---

src/common/datatypes/Value.cpp
src/common/datatypes/test/ValueTest.cpp
src/common/expression/LogicalExpression.cpp
src/common/expression/test/ExpressionTest.cpp

This PR modified LogicalExpression's behavior from the following three aspects：
```
- Fix the logical expression(AND/OR/XOR) behavior to be consistent with Cypher when null expression is involved, refer to `https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf` (search label : `Logical operations with null`).
- Add BadNull expression check
- Add empty expression check
- Add empty check for Value::operator&/|/^
```

Fix logical expression

---

src/common/plugin/fulltext/FTUtils.h
src/common/plugin/fulltext/elasticsearch/ESGraphAdapter.cpp
src/common/plugin/fulltext/elasticsearch/ESStorageAdapter.cpp

Full-text index insert and scan will fail when single quotes appear in property values. reason is : 
The single quotes conflict  beteen `-d '` and `dev's`
invalid http body:
`-d '{"query": {"bool": {"must": [{"prefix": {"value": "dev's work"}}]}},"_source": ["value"],"from": 0,"size": 100}'`
valid http body:
`-d '{"query": {"bool": {"must": [{"prefix": {"value": "dev'\''s work"}}]}},"_source": ["value"],"from": 0,"size": 100}'`
- fixed the error as below :

fixed single quote error for fulltext index

---

src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

This may happen if an RPC arrived to a storage, whose leader is not elected.

if storage rpc return leader_change, but not set leader host, may core

---

src/common/datatypes/ListOps.h
src/common/datatypes/MapOps.h
src/common/datatypes/SetOps.h
src/common/datatypes/ValueOps.h
src/common/interface/common.thrift

Add prefix `N` to `List/Map/Set` to prevent naming conflicts. The only exception is C++ for the sake of minimal changes at the server side.
This PR will impact on all of our client API except C++, thus CI of nebula-graph due to nebula-python and nebula-console due to nebula-go

Rename typename of containers in thrift

---

src/common/base/Base.h
src/common/clients/storage/GraphStorageClient.cpp
src/common/interface/storage.thrift

Explicit is better than implicit.
Previously, storage has many default return columns. For example, `fetch tag` will always return vid as first column. `lookup edge` will always return src, rank and dst as first three columns. This will cause many problems, for example, query engine will need to distinguish `DataSet` is from fetch or lookup. Both query engine and storage will have special cases to deal with.
In this PR:
1. *Storage will no more return any default columns. Any columns need to specified explicitly by query engine or client.*
For example, you can specify `kVid`, `kTag` or any column in tag schema to get the property you want in `VertexProp`. And `kSrc/kType/kRank/kDst` and any column in edge schema in `EdgeProp`. 
The return column of lookup will be specified in …

unify all storage interface behavior

---

src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

now getResponse() will call itself recursively. 
but in the second level. 
```
auto f = pro.getFuture(); 
```
will throw exception,  because get future from the same promise.

getResponse throw not appropriate exception if leader changed

---

src/common/webservice/WebService.cpp

fixed bug : NG-359
Metad crashed when http addr:port already in use.

fixed metad dump when port already in use

---

CMakeLists.txt
cmake/ThriftGenerate.cmake

This PR fixes two issues:
* Thrift codegen is performed multiple times in parallel build.
* Storage related sources might be built twice even nothing changed.
The reasons are:
* `add_custom_command` iteself does not introduce a target.
* Multiple targets depend on the generated files, i.e. the generating procedure, while these targets don't depend on each other. So the codegen will be invoked in each depending chain.
* storage.thrift depends on meta.thrift just like common.thrift, but the dependency is not addressed explicitly.

Fix parallel thrift codegen

---

cmake/nebula/GitInfoConfig.cmake

ccache use **the command line options** to compute the cache hash value, so if git info sha changes each time, it'll increase the cache misses for object files.

Remove the GIT_INFO_SHA definition from compile option

---

src/common/clients/storage/InternalStorageClient.cpp
src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

The current storage client retry mechanism is completely wrong.
For example
1）a host's request contains 2 parts, a part succeeds, the other has leader change,
2）a host's request contains 3 parts, one part is successful, and the other two parts have leader change, and these two parts correspond to two leaders respectivelys.
In two way, how many times the request is retried is always an error. Retrying is completely invalid.
There are two solutions:
1) The storage client does not retry, modify the leader host of all the parts of the leader change, so the next time you re-execute sql, it will succeed
2) Storage client retry. When the errcode in the same request is leader change, it will retry, otherwise it will not retry. Need to reorganize the leader change requst in the same request of …

storage client no retry， retry is completely invalid.

---

src/common/clients/storage/StorageClientBase.inl

when leader changed, 
collectResponse only set error code to StorageRpcResponse::responses_
but not append error code to failedParts_.
Which means if the caller not check responses_, it may get a succeeded result.

reveal the hidden leader changed error code

---

src/common/clients/meta/MetaClient.cpp

1. Previously, leader info only send to meta when it changed, which will cause `show host` or `show parts` is missing something if heartbeat with leader info failed. Talked with @sherman-the-tank offline, always send is ok. 
2. Unify default value of `heartbeat_interval_secs` in gflags and conf.

always send storage leaders to meta

---

src/common/datatypes/Value.cpp
src/common/datatypes/Value.h
src/common/datatypes/test/ValueTest.cpp
src/common/expression/TypeCastingExpression.cpp
src/common/expression/test/ExpressionTest.cpp
src/common/function/FunctionManager.cpp
src/common/function/test/FunctionManagerTest.cpp

This PR fixes TypeCastExpression behavior(refer to: [openCypher scalar functions](https://neo4j.com/docs/cypher-manual/current/functions/scalar/#functions-toboolean )) and add functions related with type conversion.
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/746](https://github.com/vesoft-inc/nebula-graph/pull/746) and [https://github.com/vesoft-inc/nebula-storage/pull/352](https://github.com/vesoft-inc/nebula-storage/pull/352)
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/677](https://github.com/vesoft-inc/nebula-graph/issues/677) and [https://github.com/vesoft-inc/nebula-graph/issues/706](https://github.com/vesoft-inc/nebula-graph/issues/706)
---
Note:
```
Value::toBool() 行为有如下变动:
- 除 null/bool/string 之外的类型视为非法类型，返回 kNullBadType
- bool 类型原样返回
- 字符串 …
```

Fix TypeCastExpression

---

cmake/nebula/ConfigNebulaCommon.cmake
src/common/http/HttpClient.cpp
src/common/http/HttpClient.h
src/common/stats/StatsManager.cpp
src/common/webservice/GetFlagsHandler.cpp
src/common/webservice/GetFlagsHandler.h
src/common/webservice/GetStatsHandler.cpp
src/common/webservice/GetStatsHandler.h
src/common/webservice/SetFlagsHandler.cpp
src/common/webservice/SetFlagsHandler.h
src/common/webservice/WebService.cpp
src/common/webservice/test/FlagsAccessTest.cpp
src/common/webservice/test/StatsReaderTest.cpp
src/common/webservice/test/TestUtils.h

This PR is originally proposed by @yixinglu :https://github.com/vesoft-inc/nebula/pull/1636
Two major changes:
1. Change update related http method to PUT and allow to update multiple flags in one time.
2. Rename GET API's filter condition like: GET graph/flags?names=minloglevel.
Related PR: https://github.com/vesoft-inc/nebula-storage/pull/354

Make flags/stats/status HTTP API confirm to RESTful specification

---

src/common/datatypes/Path.h
src/common/datatypes/Value.cpp
src/common/datatypes/Value.h
src/common/datatypes/test/ValueTest.cpp
src/common/expression/RelationalExpression.cpp
src/common/expression/test/ExpressionTest.cpp

This PR fixes some bugs about Value comparison related to `null` and `empty`.  Fixes https://github.com/vesoft-inc/nebula-graph/issues/644
There are some test cases:
- 2>true : null   2<=true : null
- 2==true : false
- null==true : null
- null<>null : null
- empty==empty : true
- empty==null : null
- empty>=1 : empty

fix RelationalExpression

---

src/common/thrift/ThriftClientManager.inl

Fix `ThriftClientManager` will return nullptr in #431, it would make all places to handle exception. We just return a bad connection when resolved failed, and wait retry later just like previous behavior.

fix nullptr ThriftClient

---

src/common/clients/meta/MetaClient.cpp
src/common/clients/meta/MetaClient.h
src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

1. When we don't know who is leader, select in round-robin. Previously random will make us need to retry several times(some query like `lookup` need to access all leaders), until we random pick a live storage for all partition (which is hard if we have a lot partitions, I tried for 10+ times when 100 partitions). In round-robin ways, we only need to retry for a limited times if we encounter leader change.

select leader in round-robin

---

src/common/clients/storage/GraphStorageClient.cpp
src/common/clients/storage/InternalStorageClient.cpp
src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

https://confluence.nebula-graph.io/pages/viewpage.action?pageId=9666582#id-%E6%80%A7%E8%83%BD%E8%B0%83%E4%BC%98-CASE4

Improve clusterIdsToHosts.

---

src/common/base/SlowOpTracker.h
src/common/thrift/ThriftClientManager.inl

The invalid channel log will print logs forever, especially for raft client. (chaos test will kill storage)

Lower ThriftClientManager log level

---

src/common/expression/AggregateExpression.h
src/common/expression/test/ExpressionTest.cpp
src/common/function/AggFunctionManager.cpp
src/common/function/test/AggFunctionManagerTest.cpp

Reverts vesoft-inc/nebula-common#477

Revert "fix agg"

---

src/common/expression/AggregateExpression.cpp
src/common/expression/AggregateExpression.h
src/common/expression/test/AggregateExpressionBenchmark.cpp
src/common/expression/test/CMakeLists.txt

> 
Add aggregateExpression's runtime cache.Just Follow [https://github.com/vesoft-inc/nebula-common/pull/407](https://github.com/vesoft-inc/nebula-common/pull/407) to achieve this.
---
Benchmark:
Before this PR:
After this PR:

Add agg cache

---

src/common/plugin/fulltext/FTUtils.h

fixed fulltext security error.
the curl command parse error for user name and password. a space character is missing.

fixed fulltext security error

---

src/common/function/FunctionManager.cpp
src/common/function/test/FunctionManagerTest.cpp

refer to https://github.com/vesoft-inc/nebula-graph/issues/878

fix substr crash

---

src/common/function/FunctionManager.cpp
src/common/function/test/FunctionManagerTest.cpp

support `timestamp()` to take empty arguments. The functionality is the same as `now()`.
Fixes https://github.com/vesoft-inc/nebula-graph/issues/811

[OpenCypher Compatibility] Support timestamp() with empty parameter

---

src/common/clients/meta/MetaClient.cpp

Steps to reproduce this issue:
1. create a index:
(root@nebula) [basketballplayer]> create tag index name on player(name(20));
Execution succeeded (time spent 2989/3376 us)
2. drop the index:
(root@nebula) [basketballplayer]> drop tag index name
Execution succeeded (time spent 2750/3179 us)
3. create the index again:
(root@nebula) [basketballplayer]> create tag index name on player(name(20));
Execution succeeded (time spent 2989/3376 us)
4. drop the index again will return fails:
(root@nebula) [basketballplayer]> drop tag index name;
[ERROR (-12)]: SemanticError: index name was not found
the root cause is that  edgeNameIndexMap_.emplace(std::move(pair), indexID) does not update edgeNameIndexMap_ as old key exists.

Fix bug: emplace only do insertion when key does not exists.

---

src/common/expression/Expression.h
src/common/expression/ListComprehensionExpression.cpp
src/common/expression/ListComprehensionExpression.h
src/common/expression/PredicateExpression.cpp
src/common/expression/PredicateExpression.h
src/common/expression/ReduceExpression.cpp
src/common/expression/ReduceExpression.h

When we print execution plan, we expect the rewrited expr string. And we can response the raw expr string result to user by this interface if needed.

Add rawString interface for expression

---

src/common/base/Base.h
src/common/datatypes/test/EdgeBenchmark.cpp
src/common/datatypes/test/ValueBenchmark.cpp
src/common/time/test/TimeUtilsTest.cpp

Build fails in arm64 box with clang. It involves folly, clang, gcc and arm neon. So it's complicated. This patch is kind of a workaround.

Workaround to fix clang build on aarch64

---

src/common/clients/meta/MetaClient.cpp
src/common/clients/meta/MetaClient.h
src/common/clients/storage/StorageClientBase.h
src/common/clients/storage/StorageClientBase.inl

Load leader info by heartbeat from meta, this feature was meant to be merged in 2.0 GA. However https://github.com/vesoft-inc/nebula-common/pull/455 involves with some behavior changes.
This PR merely move every leader process from StorageClient to MetaClient. MetaClient will update leader info once distribution changed, and storage client will modify it according storage response.

load leader info by heartbeat

---

src/common/datatypes/Value.cpp
src/common/datatypes/Value.h
src/common/datatypes/test/ValueTest.cpp

As title.
```
(root@nebula) [nba]> yield 9223372036854775807 + 1
[ERROR (-8)]: (9223372036854775807+1) cannot be represented as an integer
(root@nebula) [nba]> yield 9223372036854775807/0
[ERROR (-8)]: / by zero
```
Required by https://github.com/vesoft-inc/nebula-graph/pull/1043

Fix Integer overflow

---

src/common/expression/LabelAttributeExpression.h
src/common/expression/TextSearchExpression.h

https://discuss.nebula-graph.com.cn/t/topic/4414

Fix compile error

---

cmake/ThriftGenerate.cmake
src/common/interface/common.thrift
src/common/interface/raftex.thrift

After some digging, `process_in_event_base` has no effect for both previous and current version fbthrift, all requests received from io thread will be handled worker thread. If request do need to process in eb, need to remove `process_in_event_base` and add annotation.
Storage PR will be opened later.

raft heartbeat in eb

---

src/common/base/Memory.h
src/common/base/test/MemoryTest.cpp

`Total = Used + Free + Buffer/Cache`
Maybe need to take buffer/cache into consideration, here a screenshot when I do some test.
Graph will keep logging something like `Used memory(211303932KB) hits the high watermark(0.800000) of total system memory(263856036KB).`.
PR is still in verification.

count buffer/cache into MemInfo

---

src/common/datatypes/Date.h
src/common/datatypes/Map.h
src/common/function/AggFunctionManager.cpp
src/common/function/AggFunctionManager.h
src/common/function/FunctionManager.cpp
src/common/function/test/FunctionManagerTest.cpp
src/common/graph/Response.cpp
src/common/graph/Response.h
src/common/time/CMakeLists.txt
src/common/time/TimeConversion.cpp
src/common/time/TimeConversion.h
src/common/time/TimeUtils.cpp
src/common/time/TimeUtils.h
src/common/time/TimezoneInfo.cpp
src/common/time/TimezoneInfo.h
src/common/time/test/TimeUtilsTest.cpp

Expose the time utils which used in cpp-client.

Expose time utils.

---

src/common/datatypes/Value.cpp
src/common/datatypes/test/ValueTest.cpp

As title.
The result should not present the float value as a fixed-digits value.
Close https://github.com/vesoft-inc/nebula-graph/issues/1214

Fix operator+ for string and float

---

src/common/expression/SubscriptExpression.cpp
src/common/expression/test/SubscriptExpressionTest.cpp

1. simplify the code;
2. fix the wrong eval for this case:
```
return [0,1,2,3,4,5][-2..]
```
wrong result:
[4]
proper result:
[4,5]

fix and simplify SubscriptRangeExpression's eval()

---

src/common/datatypes/Value.cpp
src/common/datatypes/test/ValueTest.cpp

1. Fix incorrect result
2. Add overflow check when parsing string
Fix https://github.com/vesoft-inc/nebula-graph/issues/1284

Fix toInteger()

---

src/common/datatypes/Map.h
src/common/expression/AttributeExpression.cpp
src/common/expression/test/AggregateExpressionTest.cpp
src/common/expression/test/AttributeExpressionTest.cpp
src/common/expression/test/SubscriptExpressionTest.cpp
src/common/function/AggFunctionManager.cpp
src/common/time/TimeUtils.h

We shouldn't process the bad null different with null, they are all null in computation.

Support to get attribute of date/time/datetime.
